// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3YSfMxx6a2F4-hUC_oOwCBgNI0bOguOs',
    appId: '1:311804233920:web:54a232dfc5243bef528525',
    messagingSenderId: '311804233920',
    projectId: 'pokeprueba-3ea8a',
    authDomain: 'pokeprueba-3ea8a.firebaseapp.com',
    databaseURL: 'https://pokeprueba-3ea8a.firebaseio.com',
    storageBucket: 'pokeprueba-3ea8a.appspot.com',
    measurementId: 'G-4JF13NEC1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR944VT0i3-vcrVtk0FX8xuVXVk6TgLRE',
    appId: '1:311804233920:android:34d52648f03e0118528525',
    messagingSenderId: '311804233920',
    projectId: 'pokeprueba-3ea8a',
    databaseURL: 'https://pokeprueba-3ea8a.firebaseio.com',
    storageBucket: 'pokeprueba-3ea8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMmxp4-mogLugbZ4_iXuYak55a_MqiZqc',
    appId: '1:311804233920:ios:1d107813ab5e2512528525',
    messagingSenderId: '311804233920',
    projectId: 'pokeprueba-3ea8a',
    databaseURL: 'https://pokeprueba-3ea8a.firebaseio.com',
    storageBucket: 'pokeprueba-3ea8a.appspot.com',
    iosClientId: '311804233920-s79i2ok2a45tig0oujambring8j5jj56.apps.googleusercontent.com',
    iosBundleId: 'com.example.domifiretemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMmxp4-mogLugbZ4_iXuYak55a_MqiZqc',
    appId: '1:311804233920:ios:1d107813ab5e2512528525',
    messagingSenderId: '311804233920',
    projectId: 'pokeprueba-3ea8a',
    databaseURL: 'https://pokeprueba-3ea8a.firebaseio.com',
    storageBucket: 'pokeprueba-3ea8a.appspot.com',
    iosClientId: '311804233920-s79i2ok2a45tig0oujambring8j5jj56.apps.googleusercontent.com',
    iosBundleId: 'com.example.domifiretemplate',
  );
}
